# frozen_string_literal: true

module Biblioxml
  module Books
    BOOKS = {
      1  => { bname: "Genesis",         bsname: "Gen" },
      2  => { bname: "Exodus",          bsname: "Exod" },
      3  => { bname: "Leviticus",       bsname: "Lev" },
      4  => { bname: "Numbers",         bsname: "Num" },
      5  => { bname: "Deuteronomy",     bsname: "Deut" },
      6  => { bname: "Joshua",          bsname: "Josh" },
      7  => { bname: "Judges",          bsname: "Judg" },
      8  => { bname: "Ruth",            bsname: "Ruth" },
      9  => { bname: "1 Samuel",        bsname: "1Sam" },
      10 => { bname: "2 Samuel",        bsname: "2Sam" },
      11 => { bname: "1 Kings",         bsname: "1Kgs" },
      12 => { bname: "2 Kings",         bsname: "2Kgs" },
      13 => { bname: "1 Chronicles",    bsname: "1Chr" },
      14 => { bname: "2 Chronicles",    bsname: "2Chr" },
      15 => { bname: "Ezra",            bsname: "Ezra" },
      16 => { bname: "Nehemiah",        bsname: "Neh" },
      17 => { bname: "Esther",          bsname: "Esth" },
      18 => { bname: "Job",             bsname: "Job" },
      19 => { bname: "Psalms",          bsname: "Ps" },
      20 => { bname: "Proverbs",        bsname: "Prov" },
      21 => { bname: "Ecclesiastes",    bsname: "Eccl" },
      22 => { bname: "Song of Solomon", bsname: "Song" },
      23 => { bname: "Isaiah",          bsname: "Isa" },
      24 => { bname: "Jeremiah",        bsname: "Jer" },
      25 => { bname: "Lamentations",    bsname: "Lam" },
      26 => { bname: "Ezekiel",         bsname: "Ezek" },
      27 => { bname: "Daniel",          bsname: "Dan" },
      28 => { bname: "Hosea",           bsname: "Hos" },
      29 => { bname: "Joel",            bsname: "Joel" },
      30 => { bname: "Amos",            bsname: "Amos" },
      31 => { bname: "Obadiah",         bsname: "Obad" },
      32 => { bname: "Jonah",           bsname: "Jonah" },
      33 => { bname: "Micah",           bsname: "Mic" },
      34 => { bname: "Nahum",           bsname: "Nah" },
      35 => { bname: "Habakkuk",        bsname: "Hab" },
      36 => { bname: "Zephaniah",       bsname: "Zeph" },
      37 => { bname: "Haggai",          bsname: "Hag" },
      38 => { bname: "Zechariah",       bsname: "Zech" },
      39 => { bname: "Malachi",         bsname: "Mal" },
      40 => { bname: "Matthew",         bsname: "Matt" },
      41 => { bname: "Mark",            bsname: "Mark" },
      42 => { bname: "Luke",            bsname: "Luke" },
      43 => { bname: "John",            bsname: "John" },
      44 => { bname: "Acts",            bsname: "Acts" },
      45 => { bname: "Romans",          bsname: "Rom" },
      46 => { bname: "1 Corinthians",   bsname: "1Cor" },
      47 => { bname: "2 Corinthians",   bsname: "2Cor" },
      48 => { bname: "Galatians",       bsname: "Gal" },
      49 => { bname: "Ephesians",       bsname: "Eph" },
      50 => { bname: "Philippians",     bsname: "Phil" },
      51 => { bname: "Colossians",      bsname: "Col" },
      52 => { bname: "1 Thessalonians", bsname: "1Thess" },
      53 => { bname: "2 Thessalonians", bsname: "2Thess" },
      54 => { bname: "1 Timothy",       bsname: "1Tim" },
      55 => { bname: "2 Timothy",       bsname: "2Tim" },
      56 => { bname: "Titus",           bsname: "Titus" },
      57 => { bname: "Philemon",        bsname: "Phlm" },
      58 => { bname: "Hebrews",         bsname: "Heb" },
      59 => { bname: "James",           bsname: "Jas" },
      60 => { bname: "1 Peter",         bsname: "1Pet" },
      61 => { bname: "2 Peter",         bsname: "2Pet" },
      62 => { bname: "1 John",          bsname: "1John" },
      63 => { bname: "2 John",          bsname: "2John" },
      64 => { bname: "3 John",          bsname: "3John" },
      65 => { bname: "Jude",            bsname: "Jude" },
      66 => { bname: "Revelation",      bsname: "Rev" }
    }.freeze
  end
end
